version: 2
updates:
- package-ecosystem: npm
  directory: "/ember"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - velrest
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
    - 10.4.1
  - dependency-name: ember-caluma
    versions:
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
  - dependency-name: ember-template-lint
    versions:
    - 3.0.0
    - 3.0.1
    - 3.1.0
    - 3.1.1
    - 3.2.0
  - dependency-name: ember-cli-babel
    versions:
    - 7.24.0
    - 7.25.0
    - 7.26.0
  - dependency-name: ember-concurrency
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.2
  - dependency-name: ember-cli-app-version
    versions:
    - 4.0.0
  - dependency-name: ember-apollo-client
    versions:
    - 3.0.2
    - 3.0.3
  - dependency-name: sass
    versions:
    - 1.32.6
